### ISSUE TITLE
amber_eval.sh for AMBER dataset

### ISSUE THREAD

**Issue by pandawynn** [sangminwoo/AvisC#6]
Thank you for sharing, your work is very interesting! By the way, could you please share the test code (i.e., the script `amber_eval.sh`) for the AMBER dataset? I would like to reproduce the results of this dataset on my local server. Thanks again! :)

**Comment by pandawynn** [comment]
Sorry! My bad.... I found the corresponding code.

**Comment by sangminwoo** [comment]
Hi @darwann, Thanks for your interest!
Glad that you found the code and I will close this issue.
